Update Scanners.md for adding new id 40037
zaproxy/zaproxy pull request #6177
Opened 2020-09-16 14:12 UTC by gdgd009xcd

add id 40037 for new my thirdparty addon: CustomActiveScanForZAP.

2020-09-16 14:15 UTC, kingthorin requested changes

2020-09-16 14:15 UTC, kingthorin commented on docs/scanners.md
> +40037   CustomActiveScanForZAP
```suggestion
40037   CustomActiveScanForZAP (3rd Party)
```

2020-09-16 14:24 UTC, psiinon approved these changes

2020-09-16 14:26 UTC, kingthorin approved these changes

2020-09-16 14:28 UTC, merged

2020-09-22 06:48 UTC, gdgd009xcd commented
thanks!
close