Support host override for local OpenAPI spec
zaproxy/zaproxy pull request #8705
Opened 2024-11-15 09:08 UTC by fgreinacher

The host override can also be useful when handling local spec. I'd say it's not too uncommon to have only the productive system in the spec. If ZAP should run against a staging or development environment system the `-O` option comes in handy.

:hammer_and_pick: with :heart: by [Siemens](https://opensource.siemens.com/)

2024-11-15 09:15 UTC, thc202 commented
https://github.com/zaproxy/zaproxy/pull/8445

2024-11-22 18:11 UTC, thc202 commented
Can you update the changelog and accept the CLA?

2024-11-27 20:31 UTC, fgreinacher commented
I have adapted the changelog. Still waiting for the OK from our legal team regarding the CLA.

2024-11-29 09:19 UTC, fgreinacher commented
I have read the CLA Document and I hereby sign the CLA

2024-11-29 09:20 UTC, fgreinacher commented
> Can you update the changelog and accept the CLA?

@thc202 All done. Let me know if something else needs to be adapted.

2025-03-24 18:00 UTC, psiinon requested changes

2025-03-24 18:00 UTC, psiinon commented on docker/zap-api-scan.py
> +
I dont think that moving this code has the effect you want. 
The `res = zap.openapi.import_file(target_file)` line does the actual importing, and that does not support the host override option.
The openapi add-on will also have to change in order to override the hosts for local files.

2025-03-25 09:20 UTC, psiinon commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [0dcc9562\-594a\-454c\-a77d\-60b37cdc8751](https://eu.ast.checkmarx.net/projects/641c4d0f-0dae-4786-973b-ead9338157fd/scans?id=0dcc9562-594a-454c-a77d-60b37cdc8751&branch=fgreinacher%2Fhost-override-file)
### Great job, no security vulnerabilities found in this Pull Request

2025-03-25 10:33 UTC, psiinon approved these changes

2025-03-25 11:27 UTC, kingthorin approved these changes
TY both

2025-03-25 11:27 UTC, merged